import journalImg from "../../assets/images/journalImg.jpeg";

const propertiesData = [
  {
    img: journalImg,
    name: "Palm Jumeirah",
    title: "Six Senses Residences",
    info: "BHM-S-552274",
    bed: "5 bed",
    bath: "7 bath",
    fit: "16016 sq. ft.",
    price: "AED 93,000,000",
  },
  {
    img: journalImg,
    name: "Palm Jumeirah",
    title: "Six Senses Residences",
    info: "BHM-S-552274",
    bed: "5 bed",
    bath: "7 bath",
    fit: "16016 sq. ft.",
    price: "AED 93,000,000",
  },
  {
    img: journalImg,
    name: "Palm Jumeirah",
    title: "Six Senses Residences",
    info: "BHM-S-552274",
    bed: "5 bed",
    bath: "7 bath",
    fit: "16016 sq. ft.",
    price: "AED 93,000,000",
  },
  {
    img: journalImg,
    name: "Palm Jumeirah",
    title: "Six Senses Residences",
    info: "BHM-S-552274",
    bed: "5 bed",
    bath: "7 bath",
    fit: "16016 sq. ft.",
    price: "AED 93,000,000",
  },
  {
    img: journalImg,
    name: "Palm Jumeirah",
    title: "Six Senses Residences",
    info: "BHM-S-552274",
    bed: "5 bed",
    bath: "7 bath",
    fit: "16016 sq. ft.",
    price: "AED 93,000,000",
  },
  {
    img: journalImg,
    name: "Palm Jumeirah",
    title: "Six Senses Residences",
    info: "BHM-S-552274",
    bed: "5 bed",
    bath: "7 bath",
    fit: "16016 sq. ft.",
    price: "AED 93,000,000",
  },
  {
    img: journalImg,
    name: "Palm Jumeirah",
    title: "Six Senses Residences",
    info: "BHM-S-552274",
    bed: "5 bed",
    bath: "7 bath",
    fit: "16016 sq. ft.",
    price: "AED 93,000,000",
  },
  {
    img: journalImg,
    name: "Palm Jumeirah",
    title: "Six Senses Residences",
    info: "BHM-S-552274",
    bed: "5 bed",
    bath: "7 bath",
    fit: "16016 sq. ft.",
    price: "AED 93,000,000",
  },
  {
    img: journalImg,
    name: "Palm Jumeirah",
    title: "Six Senses Residences",
    info: "BHM-S-552274",
    bed: "5 bed",
    bath: "7 bath",
    fit: "16016 sq. ft.",
    price: "AED 93,000,000",
  },
];

export default propertiesData;
